### ISSUE TITLE
Installation fails at "Generate Nexus types"

### ISSUE THREAD

**Issue by fraherm** [echobind/bisonapp#24]
I did a new installation with `yarn create bison-app bison-test` and the process stopped at "Generate Nexus types" due to an error.

**1. `yarn create bison-app bison-test`**
```
  ✔ Copy files
  ✔ Install dependencies
  ✖ Generate Nexus types
    → info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    Cleanup
    Git init
(node:50408) UnhandledPromiseRejectionWarning: Error: Command failed: yarn nexus build --no-bundle
error Command failed with exit code 1.

yarn run v1.22.4
$ /Users/frank/Documents/test/bison-test/node_modules/.bin/nexus build --no-bundle
{"event":"get used plugins","level":3,"path":["nexus","build"]}
{"event":"failed to get used plugins","level":6,"path":["nexus"],"context":{"error":{}}}
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

    at makeError (/Users/frank/.config/yarn/global/node_modules/execa/index.js:174:9)
    at /Users/frank/.config/yarn/global/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:50408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:50408) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**2. Then I tried `yarn nexus build --no-bundle` by myself which ended up in this error**

```
✕ nexus failed to get used plugins
  | error  Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
  |        In case this error is unexpected for you, please report it in https://github.com/prisma/prisma-client-js/issues/390.
  |            at new PrismaClient (/Users/frank/Documents/test/bison-test/node_modules/.prisma/client/index.js:3:11)
  |            at Object.<anonymous> (/Users/frank/Documents/test/bison-test/lib/prisma.ts:6:12)
  |            at Module._compile (internal/modules/cjs/loader.js:1251:30)
  |            at Module._compile (/Users/frank/Documents/test/bison-test/node_modules/pirates/lib/index.js:99:24)
  |            at Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
  |            at Object.newLoader [as .ts] (/Users/frank/Documents/test/bison-test/node_modules/pirates/lib/index.js:104:7)
  |            at Module.load (internal/modules/cjs/loader.js:1100:32)
  |            at Function.Module._load (internal/modules/cjs/loader.js:962:14)
  |            at Module.require (internal/modules/cjs/loader.js:1140:19)
  |            at require (internal/modules/cjs/helpers.js:75:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**3. `yarn global add @prisma/client && prisma generate`**

**4. `yarn nexus build --no-bundle` worked as expected**

I think `prisma generate` should be run before `nexus build --no-bundle`. What do you say?

**Comment by cball** [comment]
sorry about that @fraherm! Thanks for reporting. We'll release a fix shortly.

**Comment by fraherm** [comment]
No worries and thank you for fixing this so fast!
