### ISSUE TITLE
Vercel deployment - Required lambda files exceed max lambda size

### ISSUE THREAD

**Issue by MarvinAmador7** [echobind/bisonapp#28]
I was trying to deploy an untouched and fresh installation of bison app to Vercel but I'm getting a `Required lambda files exceed max lambda size` error

![image](https://user-images.githubusercontent.com/13001660/90573787-8f9b5880-e174-11ea-8562-12bc38fb3fff.png)

this is the full deployment log:

```

16:49:36 | Cloning github.com/MarvinAmador7/haab (Branch: master, Commit: 5a8033d)
-- | --
16:49:54 | Cloning completed in 17010ms
16:49:54 | Analyzing source code...
16:50:10 | Installing build runtime...
16:50:10 | Build runtime installed: 406.275ms
16:50:11 | Looking up build cache...
16:50:11 | Build cache not found
16:50:11 | Installing dependencies...
16:50:12 | yarn install v1.22.4
16:50:12 | [1/4] Resolving packages...
16:50:12 | [2/4] Fetching packages...
16:50:12 | warning Pattern ["@apollo/client@latest"] is trying to unpack in the same destination "/vercel/.cache/yarn/v6/npm-@apollo-client-3.1.3-4ea9c3818bd2836a3dbe26088227c3d8cb46ad2b-integrity/node_modules/@apollo/client" as pattern ["@apollo/client@^3.0.2"]. This could result in non-deterministic behavior, skipping.
16:50:34 | info fsevents@1.2.13: The platform "linux" is incompatible with this module.
16:50:34 | info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
16:50:34 | info fsevents@2.1.3: The platform "linux" is incompatible with this module.
16:50:34 | info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
16:50:34 | [3/4] Linking dependencies...
16:50:34 | warning " > @apollo/client@3.1.3" has unmet peer dependency "graphql@^14.0.0 \|\| ^15.0.0".
16:50:34 | warning " > @apollo/client@3.1.3" has unmet peer dependency "subscriptions-transport-ws@^0.9.0".
16:50:34 | warning "@apollo/client > graphql-tag@2.11.0" has unmet peer dependency "graphql@^0.9.0 \|\| ^0.10.0 \|\| ^0.11.0 \|\| ^0.12.0 \|\| ^0.13.0 \|\| ^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/accordion@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/alert@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/alert-dialog@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/avatar@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/breadcrumb@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/button@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/checkbox@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/close-button@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/collapse@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/drawer@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/editable@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/form-control@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/icon@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/image@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/input@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/layout@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/media-query@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/menu@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/modal@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/number-input@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/pin-input@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/popover@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/progress@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/radio@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/select@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/slider@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/spinner@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/stat@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/switch@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/tabs@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/tag@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/textarea@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning " > @chakra-ui/theme@1.0.0-rc.2" has unmet peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/toast@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/tooltip@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/transition@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning "@chakra-ui/core > @chakra-ui/visually-hidden@1.0.0-rc.2" has incorrect peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning " > @chakra-ui/theme-tools@1.0.0-rc.2" has unmet peer dependency "@chakra-ui/system@1.0.0-rc.1".
16:50:34 | warning " > graphql-iso-date@3.6.1" has unmet peer dependency "graphql@^0.5.0 \|\| ^0.6.0 \|\| ^0.7.0 \|\| ^0.8.0-b \|\| ^0.9.0 \|\| ^0.10.0 \|\| ^0.11.0 \|\| ^0.12.0 \|\| ^0.13.0 \|\| ^14.0.0".
16:50:34 | warning " > graphql-type-json@0.3.2" has unmet peer dependency "graphql@>=0.8.0".
16:50:34 | warning "nexus > @zeit/node-file-trace > acorn-export-ns-from@0.1.0" has incorrect peer dependency "acorn@^6.0.1".
16:50:34 | warning " > @graphql-codegen/cli@1.17.6" has unmet peer dependency "graphql@^0.8.0 \|\| ^0.9.0 \|\| ^0.10.0 \|\| ^0.11.0 \|\| ^0.12.0 \|\| ^0.13.0 \|\| ^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "@graphql-codegen/cli > @graphql-codegen/core@1.17.6" has unmet peer dependency "graphql@^0.8.0 \|\| ^0.9.0 \|\| ^0.10.0 \|\| ^0.11.0 \|\| ^0.12.0 \|\| ^0.13.0 \|\| ^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "@graphql-codegen/cli > @graphql-codegen/plugin-helpers@1.17.6" has unmet peer dependency "graphql@^0.8.0 \|\| ^0.9.0 \|\| ^0.10.0 \|\| ^0.11.0 \|\| ^0.12.0 \|\| ^0.13.0 \|\| ^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "@graphql-codegen/cli > @graphql-tools/apollo-engine-loader@6.0.18" has unmet peer dependency "graphql@^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "@graphql-codegen/cli > @graphql-tools/code-file-loader@6.0.18" has unmet peer dependency "graphql@^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "@graphql-codegen/cli > @graphql-tools/git-loader@6.0.18" has unmet peer dependency "graphql@^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "@graphql-codegen/cli > @graphql-tools/github-loader@6.0.18" has unmet peer dependency "graphql@^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "@graphql-codegen/cli > @graphql-tools/graphql-file-loader@6.0.18" has unmet peer dependency "graphql@^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "@graphql-codegen/cli > @graphql-tools/json-file-loader@6.0.18" has unmet peer dependency "graphql@^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "@graphql-codegen/cli > @graphql-tools/load@6.0.18" has unmet peer dependency "graphql@^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "@graphql-codegen/cli > @graphql-tools/prisma-loader@6.0.18" has unmet peer dependency "graphql@^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "@graphql-codegen/cli > @graphql-tools/url-loader@6.0.18" has unmet peer dependency "graphql@^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "@graphql-codegen/cli > @graphql-tools/utils@6.0.18" has unmet peer dependency "graphql@^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "@graphql-codegen/cli > graphql-config@3.0.3" has unmet peer dependency "graphql@^0.11.0 \|\| ^0.12.0 \|\| ^0.13.0 \|\| ^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "@graphql-codegen/cli > @graphql-codegen/core > @graphql-tools/merge@6.0.18" has unmet peer dependency "graphql@^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "@graphql-codegen/cli > @graphql-tools/code-file-loader > @graphql-tools/graphql-tag-pluck@6.0.18" has unmet peer dependency "graphql@^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "@graphql-codegen/cli > @graphql-tools/graphql-file-loader > @graphql-tools/import@6.0.18" has unmet peer dependency "graphql@^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "@graphql-codegen/cli > @graphql-tools/prisma-loader > graphql-request@3.0.0" has unmet peer dependency "graphql@14.x \|\| 15.x".
16:50:34 | warning "@graphql-codegen/cli > @graphql-tools/url-loader > @graphql-tools/delegate@6.0.18" has unmet peer dependency "graphql@^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "@graphql-codegen/cli > @graphql-tools/url-loader > @graphql-tools/wrap@6.0.18" has unmet peer dependency "graphql@^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "@graphql-codegen/cli > @graphql-tools/url-loader > subscriptions-transport-ws@0.9.17" has unmet peer dependency "graphql@>=0.10.0".
16:50:34 | warning "@graphql-codegen/cli > @graphql-codegen/core > @graphql-tools/merge > @graphql-tools/schema@6.0.18" has unmet peer dependency "graphql@^14.0.0 \|\| ^15.0.0".
16:50:34 | warning " > @graphql-codegen/typescript@1.17.6" has unmet peer dependency "graphql@^0.12.0 \|\| ^0.13.0 \|\| ^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "@graphql-codegen/typescript > @graphql-codegen/visitor-plugin-common@1.17.6" has unmet peer dependency "graphql@^0.8.0 \|\| ^0.9.0 \|\| ^0.10.0 \|\| ^0.11.0 \|\| ^0.12.0 \|\| ^0.13.0 \|\| ^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "@graphql-codegen/typescript > @graphql-codegen/visitor-plugin-common > @graphql-tools/relay-operation-optimizer@6.0.15" has unmet peer dependency "graphql@^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "@graphql-codegen/typescript > @graphql-codegen/visitor-plugin-common > graphql-tag@2.10.4" has unmet peer dependency "graphql@^0.9.0 \|\| ^0.10.0 \|\| ^0.11.0 \|\| ^0.12.0 \|\| ^0.13.0 \|\| ^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "@graphql-codegen/typescript > @graphql-codegen/visitor-plugin-common > @graphql-tools/relay-operation-optimizer > @graphql-tools/utils@6.0.15" has unmet peer dependency "graphql@^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "@graphql-codegen/typescript > @graphql-codegen/visitor-plugin-common > @graphql-tools/relay-operation-optimizer > relay-compiler@10.0.0" has unmet peer dependency "graphql@^15.0.0".
16:50:34 | warning " > @graphql-codegen/typescript-operations@1.17.8" has unmet peer dependency "graphql@^0.8.0 \|\| ^0.9.0 \|\| ^0.10.0 \|\| ^0.11.0 \|\| ^0.12.0 \|\| ^0.13.0 \|\| ^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "@graphql-codegen/typescript-operations > @graphql-codegen/plugin-helpers@1.17.8" has unmet peer dependency "graphql@^0.8.0 \|\| ^0.9.0 \|\| ^0.10.0 \|\| ^0.11.0 \|\| ^0.12.0 \|\| ^0.13.0 \|\| ^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "@graphql-codegen/typescript-operations > @graphql-codegen/typescript@1.17.8" has unmet peer dependency "graphql@^0.12.0 \|\| ^0.13.0 \|\| ^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "@graphql-codegen/typescript-operations > @graphql-codegen/visitor-plugin-common@1.17.13" has unmet peer dependency "graphql@^0.8.0 \|\| ^0.9.0 \|\| ^0.10.0 \|\| ^0.11.0 \|\| ^0.12.0 \|\| ^0.13.0 \|\| ^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "@graphql-codegen/typescript-operations > @graphql-codegen/visitor-plugin-common > @graphql-tools/relay-operation-optimizer@6.0.18" has unmet peer dependency "graphql@^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "@graphql-codegen/typescript-operations > @graphql-codegen/visitor-plugin-common > @graphql-tools/relay-operation-optimizer > relay-compiler@10.0.1" has unmet peer dependency "graphql@^15.0.0".
16:50:34 | warning " > @graphql-codegen/typescript-react-apollo@1.17.6" has unmet peer dependency "graphql@^0.8.0 \|\| ^0.9.0 \|\| ^0.10.0 \|\| ^0.11.0 \|\| ^0.12.0 \|\| ^0.13.0 \|\| ^14.0.0 \|\| ^15.0.0".
16:50:34 | warning " > @graphql-codegen/typescript-react-apollo@1.17.6" has unmet peer dependency "graphql-tag@^2.0.0".
16:50:34 | warning " > @graphql-codegen/typescript-resolvers@1.17.4" has unmet peer dependency "graphql@^0.8.0 \|\| ^0.9.0 \|\| ^0.10.0 \|\| ^0.11.0 \|\| ^0.12.0 \|\| ^0.13.0 \|\| ^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "@graphql-codegen/typescript-resolvers > @graphql-codegen/plugin-helpers@1.17.4" has unmet peer dependency "graphql@^0.8.0 \|\| ^0.9.0 \|\| ^0.10.0 \|\| ^0.11.0 \|\| ^0.12.0 \|\| ^0.13.0 \|\| ^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "@graphql-codegen/typescript-resolvers > @graphql-codegen/typescript@1.17.4" has unmet peer dependency "graphql@^0.12.0 \|\| ^0.13.0 \|\| ^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "@graphql-codegen/typescript-resolvers > @graphql-codegen/visitor-plugin-common@1.17.4" has unmet peer dependency "graphql@^0.8.0 \|\| ^0.9.0 \|\| ^0.10.0 \|\| ^0.11.0 \|\| ^0.12.0 \|\| ^0.13.0 \|\| ^14.0.0 \|\| ^15.0.0".
16:50:34 | warning "eslint-plugin-echobind > @typescript-eslint/eslint-plugin@2.34.0" has incorrect peer dependency "eslint@^5.0.0 \|\| ^6.0.0".
16:50:34 | warning "eslint-plugin-echobind > @typescript-eslint/parser@2.34.0" has incorrect peer dependency "eslint@^5.0.0 \|\| ^6.0.0".
16:50:34 | warning "eslint-plugin-echobind > eslint-config-react-app@5.2.1" has incorrect peer dependency "eslint@6.x".
16:50:34 | warning "eslint-plugin-echobind > eslint-config-react-app@5.2.1" has unmet peer dependency "eslint-plugin-flowtype@3.x \|\| 4.x".
16:50:34 | warning "eslint-plugin-echobind > eslint-plugin-react-hooks@2.5.1" has incorrect peer dependency "eslint@^3.0.0 \|\| ^4.0.0 \|\| ^5.0.0 \|\| ^6.0.0".
16:50:34 | warning "eslint-plugin-echobind > @react-native-community/eslint-config > @typescript-eslint/eslint-plugin@1.13.0" has incorrect peer dependency "eslint@^5.0.0".
16:50:34 | warning "eslint-plugin-echobind > @react-native-community/eslint-config > @typescript-eslint/parser@1.13.0" has incorrect peer dependency "eslint@^5.0.0".
16:50:34 | warning "eslint-plugin-echobind > @react-native-community/eslint-config > eslint-plugin-react@7.12.4" has incorrect peer dependency "eslint@^3.0.0 \|\| ^4.0.0 \|\| ^5.0.0".
16:50:34 | warning "eslint-plugin-echobind > @react-native-community/eslint-config > eslint-plugin-react-hooks@1.7.0" has incorrect peer dependency "eslint@^3.0.0 \|\| ^4.0.0 \|\| ^5.0.0 \|\| ^6.0.0".
16:50:34 | warning "eslint-plugin-echobind > @react-native-community/eslint-config > eslint-plugin-react-native@3.6.0" has incorrect peer dependency "eslint@^3.17.0 \|\| ^4 \|\| ^5".
16:50:50 | [4/4] Building fresh packages...
16:51:04 | Done in 52.77s.
16:51:04 | Running "yarn run build"
16:51:05 | yarn run v1.22.4
16:51:05 | $ yarn nexus build && next build
16:51:05 | $ /vercel/18ce53be/node_modules/.bin/nexus build
16:51:06 | {"event":"get used plugins","level":3,"path":["nexus","build"],"hostname":"ip-172-31-58-108.us-west-2.compute.internal","pid":1792,"time":1597791066118}
16:51:06 | {"event":"Running generators","level":3,"path":["nexus","plugin","nexusPluginPrisma"],"hostname":"ip-172-31-58-108.us-west-2.compute.internal","pid":1792,"time":1597791066772}
16:51:07 | {"event":"starting reflection","level":3,"path":["nexus","build"],"hostname":"ip-172-31-58-108.us-west-2.compute.internal","pid":1792,"time":1597791067596}
16:51:13 | {"event":"building typescript program","level":3,"path":["nexus","build"],"hostname":"ip-172-31-58-108.us-west-2.compute.internal","pid":1792,"time":1597791073684}
16:51:17 | {"event":"compiling a production build","level":3,"path":["nexus","build"],"hostname":"ip-172-31-58-108.us-west-2.compute.internal","pid":1792,"time":1597791077037}
16:51:17 | {"event":"bundling app","level":3,"path":["nexus","build"],"hostname":"ip-172-31-58-108.us-west-2.compute.internal","pid":1792,"time":1597791077087}
16:51:22 | {"event":"success","level":3,"path":["nexus","build"],"context":{"buildOutput":".nexus/build","time":16542},"hostname":"ip-172-31-58-108.us-west-2.compute.internal","pid":1792,"time":1597791082478}
16:51:23 | info  - Loaded env from /vercel/18ce53be/.env.local
16:51:23 | Creating an optimized production build...
16:51:23 | Attention: Next.js now collects completely anonymous telemetry regarding usage.
16:51:23 | This information is used to shape Next.js' roadmap and prioritize features.
16:51:23 | You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
16:51:23 | https://nextjs.org/telemetry
16:52:52 | Compiled successfully.
16:52:52 | Automatically optimizing pages...
16:52:53 | Page                                                           Size     First Load JS
16:52:53 | ┌ ○ /                                                          2.47 kB         153 kB
16:52:53 | ├   /_app                                                      22.9 kB         151 kB
16:52:53 | ├ ○ /404                                                       3.25 kB         154 kB
16:52:53 | ├ λ /api/graphql
16:52:53 | ├ ○ /login                                                     1.37 kB         168 kB
16:52:53 | └ ○ /signup                                                    1.48 kB         168 kB
16:52:53 | + First Load JS shared by all                                  151 kB
16:52:53 | ├ static/pages/_app.js                                       22.9 kB
16:52:53 | ├ chunks/165464d86b0119c3025e24821b29f8ff50481e84.34d6ab.js  22.3 kB
16:52:53 | ├ chunks/899a5c147de3c46772f6168851474b8978ce03a1.105cae.js  46.6 kB
16:52:53 | ├ chunks/abe2db7b0bc2a4c55a12dfb47b1361f9f6a3bcc5.f5bff6.js  10.3 kB
16:52:53 | ├ chunks/framework.c66671.js                                 40.1 kB
16:52:53 | ├ runtime/main.ba41a0.js                                     6.98 kB
16:52:53 | └ runtime/webpack.eb36d2.js                                  1.31 kB
16:52:53 | λ  (Lambda)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
16:52:53 | ○  (Static)  automatically rendered as static HTML (uses no initial props)
16:52:53 | ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
16:52:53 | Done in 108.73s.
16:53:27 | Traced Next.js serverless functions for external files in: 33451.464ms
16:53:53 | Compressed shared serverless function files: 26049.451ms
16:53:53 | Error: Required lambda files exceed max lambda size of 50000000 bytes
16:53:53 | at Object.module.exports.178.exports.build (/vercel/beeac83ffad651b3/.build-utils/.builder/node_modules/@vercel/next/dist/index.js:6977:23)
16:53:53 | at async buildStep (/var/task/sandbox-worker.js:21362:20)
16:53:53 | at async mainSub (/var/task/sandbox-worker.js:21096:9)
16:53:53 | at async main (/var/task/sandbox-worker.js:20959:5)
16:53:56 | Done with "package.json"


```

**Comment by cball** [comment]
@MarvinAmador7 🤔 I can't seem to reproduce this.  I created a new test app and immediately deployed it (https://bison-test1.cball.vercel.app and https://bison-test1.cball.vercel.app/api/graphql)

Could you try building locally with `yarn build` and check the size of /api/graphql?

```sh
.next/server/static on  master [✘?]
➜ du -sh yNpXT0Q7uds036kLkdGX9/pages/api/
 16K	yNpXT0Q7uds036kLkdGX9/pages/api/
```

Here's the build log for the app I just deployed.
```sh
21:24:06.772 | Compiled successfully.
-- | --
21:24:06.772 | Automatically optimizing pages...
21:24:08.156 | Page                                                           Size     First Load JS
21:24:08.156 | ┌ ○ /                                                          2.47 kB         153 kB
21:24:08.156 | ├   /_app                                                      22.9 kB         151 kB
21:24:08.156 | ├ ○ /404                                                       3.25 kB         154 kB
21:24:08.156 | ├ λ /api/graphql
21:24:08.156 | ├ ○ /login                                                     1.37 kB         168 kB
21:24:08.156 | └ ○ /signup                                                    1.48 kB         168 kB
21:24:08.156 | + First Load JS shared by all                                  151 kB
21:24:08.156 | ├ static/pages/_app.js                                       22.9 kB
21:24:08.156 | ├ chunks/cd887daada328e1a40bfed49828396af1a3a390b.d97d45.js  22.3 kB
21:24:08.157 | ├ chunks/d8dc30ea80a359a0135afdb744e9da6bec88323d.086b67.js  10.3 kB
21:24:08.157 | ├ chunks/e8897cfcbdb76e12f77bfe07cd814c760ad858e0.13a8f4.js  46.6 kB
21:24:08.157 | ├ chunks/framework.c66671.js                                 40.1 kB
21:24:08.157 | ├ runtime/main.902b39.js                                     6.98 kB
21:24:08.157 | └ runtime/webpack.5f6f41.js                                  1.31 kB
21:24:08.157 | λ  (Lambda)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
21:24:08.157 | ○  (Static)  automatically rendered as static HTML (uses no initial props)
21:24:08.157 | ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
21:24:08.234 | Done in 109.83s.
21:24:40.913 | Traced Next.js serverless functions for external files in: 32662.704ms
21:24:57.804 | Compressed shared serverless function files: 16889.866ms
21:24:57.953 | All serverless functions created in: 147.807ms
21:24:58.269 | Uploading build outputs...
21:25:02.739 | Build completed. Populating build cache...
21:25:28.344 | Uploading build cache [129.46 MB]...
21:25:30.320 | Build cache uploaded: 1975.286ms
21:25:30.337 | Done with "package.json"
```

**Comment by cball** [comment]
hey @MarvinAmador7. I'm curious if https://github.com/echobind/bisonapp/commit/91bc4df2fbf1a2e15d0f0e36f5e5fc4b506acb80 might have solved your issue?

Since this has been over a week without a response, we're going to go ahead and close it. If you're still having problems and can provide more specifics we're happy to look into it!
