### ISSUE TITLE
mkdir error when running yarn dev after fresh install.

### ISSUE THREAD

**Issue by agustif** [echobind/bisonapp#76]
```

[NEXT] Error: EROFS: read-only file system, mkdir '/node_modules'
[NEXT]     at Object.mkdirSync (fs.js:948:3)
[NEXT]     at createBrandNewDirectorySync (/Users/agustif/Code/nodede/node_modules/fs-jetpack/lib/dir.js:62:8)
[NEXT]     at createBrandNewDirectorySync (/Users/agustif/Code/nodede/node_modules/fs-jetpack/lib/dir.js:66:7)
[NEXT]     at Object.createBrandNewDirectorySync [as createSync] (/Users/agustif/Code/nodede/node_modules/fs-jetpack/lib/dir.js:66:7)
[NEXT]     at writeFileSync (/Users/agustif/Code/nodede/node_modules/fs-jetpack/lib/write.js:50:11)
[NEXT]     at Object.writeSync [as sync] (/Users/agustif/Code/nodede/node_modules/fs-jetpack/lib/write.js:75:3)
[NEXT]     at Object.write (/Users/agustif/Code/nodede/node_modules/fs-jetpack/lib/jetpack.js:226:13)
[NEXT]     at Object.exports.hardWriteFileSync (/Users/agustif/Code/nodede/node_modules/nexus-plugin-prisma/dist/utils.js:62:8)
[NEXT]     at doGenerate (/Users/agustif/Code/nodede/node_modules/nexus-plugin-prisma/dist/typegen/render.js:50:17)
[NEXT]     at Object.generateSync (/Users/agustif/Code/nodede/node_modules/nexus-plugin-prisma/dist/typegen/render.js:30:5) {
[NEXT]   errno: -30,
[NEXT]   syscall: 'mkdir',
[NEXT]   code: 'EROFS',
[NEXT]   path: '/node_modules'
[NEXT] }
```

**Comment by cball** [comment]
Thanks for the issue report @agustif! It looks like [this config](https://github.com/echobind/bisonapp/blob/canary/template/graphql/schema.ts#L17) is working differently than expected on your system 🤔

Can you confirm the value of `__dirname` in that file when running `yarn dev`? It should point to your `<projectRoot>/graphql` folder.
